directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_356
- CKV2_AWS_57
- CKV_AWS_341
- CKV_TF_1 #"Ensure Terraform module sources use a commit hash
- CKV_AWS_79 #Ensure Instance Metadata Service Version 1 is not enabled
- CKV_AWS_290 #Ensure IAM policies does not allow write access without constraints
- CKV_AWS_355 #Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions
- CKV2_AWS_5 #Ensure that Security Groups are attached to another resource
-
-
-
-
