directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_356
- CKV2_AWS_57
- CKV_AWS_341
- CKV2_AWS_5 #Ensure that Security Groups are attached to another resource"
- CKV_TF_1 #Ensure Terraform module sources use a commit hash"
